### ISSUE TITLE
Invitation functionality is not working properly

### ISSUE THREAD

**Issue by 0x4ym4n** [WahidNasri/hivemq-chat-extension#2]
I tried to send invitation from account A to account B, mqtt event is fired successfully but it didn't reached the second device.

**Comment by WahidNasri** [comment]
Hello,
Thank you for your interest in hivemq-chat-extension.
You have to make sure first that the invitee (account B) did receive his profile details (on the topic archivesmyid/{client id}), because after that he will subscribe to the topic personalevents/{user id} and be able to receive invitations.
I see also you raised an issue about the SQL schema being old, I made a commit fixing that, it could be an issue because the old schema did not have the invitations table, can you try again ?
Anyway I will retry the case and see if there is anything

**Comment by 0x4ym4n** [comment]
Thank you for your feedback, I will retry again.

**Comment by 0x4ym4n** [comment]
Thank you for your feedback, yes I tried it again & now it's working out of the box, I appreciate your support.
